config/routes.rb
Breakaway::Application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "marketing#splash"
  get '/about', to: 'marketing#about'
  
  devise_for :club_players, :controllers => {:registrations => "players/registrations",
                                        :sessions => "players/sessions",
                                        :passwords => "players/passwords"} 
                                        
 
  devise_for :college_coaches, :controllers => {:registrations => "coaches/registrations",
                                        :sessions => "coaches/sessions", 
                                        :passwords => "coaches/passwords"}
  authenticated :club_player do 
    resources :links    
    get '/upgrade', to: 'dashboard#upgrade'
    post '/create_link', to: 'dashboard#create_short_url', as: 'generate_short_link'    
    resources :listings, except: :show
    resources :charges
    resources :games
    patch '/cancel_subscription', to: 'dashboard#cancel_subscription'
  end
  authenticated :college_coach do
    get 'friendships/:friend_id' => 'user_friendships#new', :as => :new_friendship  
    put '/e/:profile_name', to: "profiles#email_club_coach", as: 'send_coach_email'
  end

  get "profiles/show" 
  
  get '/players', to: "profiles#index", as: 'club_players'
  get "dashboard/show"
  get "dashboard", to: "dashboard#show", as: 'dashboard'
  get "/dashboard/download_schedule", to: "dashboard#download_schedule", as: "download_schedule" #, format: 'csv'
  get "/terms", to: 'marketing#terms_and_privacy', as: 'terms'
    
  get '/t/:slug', to: 'links#show_profile'
  
  get '/:profile_name', to: "profiles#show", as: 'profile'
    
  resources :user_friendships
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :check_coach_or_player
  before_filter :authenticate_club_player!, only: [:upgrade]
  
  def upgrade
    redirect_to(dashboard_path, notice: "You are already subscribed, no need to subscribe again :)") if current_club_player.subscribed? 
  end
  
  def show
    if current_college_coach
       @profiles = current_college_coach.friends
       @favorite_games = current_college_coach.future_favorite_games
    else
      @listings = current_club_player.listings
      @games = current_club_player.games
      @player = current_club_player
      @stats = current_club_player.link.stats.order(created_at: :desc).to_a if current_club_player.link.present?
      @game = Game.new
    end
  end
  
  def download_schedule
    send_data Game.to_csv_favorites(current_college_coach.future_favorite_games)
  end
  
  def cancel_subscription
    current_club_player.cancel_subscription_plan
    redirect_to dashboard_path, notice: "You subscription has been cancelled"
  end
  
  def create_short_url
    if current_club_player.subscribed? && current_club_player.link.nil?
      link = Link.new
      link.slug = SecureRandom.urlsafe_base64(6)
      link.given_profile_url = "/" + current_club_player.profile_name
      link.club_player_id = current_club_player.id
      link.save
      redirect_to dashboard_path, notice: "Link created, check it out in the My Profile Stats tab."
    else
      redirect_to dashboard_path, notice: "Subscribe first"
    end
  end
  
  private 
  
  def check_coach_or_player
    if current_college_coach
      :authenticate_college_coach!
    elsif current_club_player
      :authenticate_club_player!
    else 
      redirect_to root_path, notice: "Must be signed in to do that"
    end
  end   
end

app/helpers/dashboard_helper.rb
module DashboardHelper  
  def subscription_helper(today=Date.today)    
    (today + 360).strftime("%m/%d/%y")    
  end
end

app/views/dashboard/_coach.html.erb
<h1 class="page-header">Dashboard</h1> 

<%= link_to 'Search All Players <i class="fa fa-long-arrow-right"></i>'.html_safe, club_players_path, class: "btn btn-link btn-lg"%>
<br><br>
<ul class="nav nav-tabs">
	<li class="active"><a href="#video_listing" data-toggle="tab">All my favorites</a></li>
	<li><a href="#schedule_listing" data-toggle="tab">All favorites upcoming games</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="video_listing">
		<div class="row">
			<br>
			<% if @profiles.size > 0 %>
				<%= render 'coach_fav' %>
			<% else %>	
				<%= render 'seed_coach_fav' %>
			<% end %>
		</div>

	</div>
	<div class="tab-pane" id="schedule_listing">
		<br />
		<%= link_to "Download this entire schedule", download_schedule_path(format: :csv) %><br><br>
		Today is <%= (Date.today).strftime("%m/%d/%Y") %>
		<br />
		<br />
	 	<table class="table table-hover">
	 		<th>Date</th>
	 		<th>Game Time</th>
			<th>Team</th>
			<th>Player</th>
	 		<th>Location</th>
	 		<th>Opponent</th>

		<% @favorite_games.each do |game| %>
		  <tr>
			  <td> <%= (game.scheduled_date).strftime("%m/%d/%Y") %></td>
			  <td> <%= game.scheduled_time %></td>
		  	  <td> <%= game.club_player.club_team %></td>
			  <td> <%= game.club_player.full_name %></td>			 			
		 	  <td> <%= game.location %></td>
		  	  <td> <%= game.opponent %></td>

		 </tr>		 
		<% end %>
		</table>
	</div>
</div>

app/views/dashboard/_coach_fav.html.erb
<br><br>
<% @profiles.each do |profile| %>

	<div class='col-md-2 col-sm-5 col-xs-5 card-wrapper-user'>
		
		<div class="row" style="text-align: center;">
			  <% if profile.listings.size > 0 %> 
			    <%= image_tag "https://i1.ytimg.com/vi/#{youtube_thumb_embed(profile.listings.last.video)}/mqdefault.jpg", class: "dash-thumb" %>
			  <% else %>
			     <h5><small>They have removed all their videos :(</small></h5>
			  <% end %>
		</div>
		<br>
		<div class="row">	  
			<ul>
				<li><%= profile.full_name %></li>
				<li><%= profile.position %> for <%= profile.club_team %></li>
				<li><%= profile.grad_year %> graduate</li>
				<li><%= profile.formation %></li>
				<li><%= link_to "View #{profile.first_name}'s Profile", profile_path(profile.profile_name) %></li>
				<li><small><%= link_to "Remove from watchlist", user_friendship_path(current_college_coach.friendship(profile)), method: :delete, data: { confirm: "Are you certain you want remove #{profile.full_name} from watchlist?" },class: "remove-player" %></small></li>
			</ul>  		     

		</div>
	</div>
<% end %>

app/views/dashboard/_game.html.erb
<br>
<%= link_to "Add new game", new_game_path, class: "btn btn-success btn-lg" %>
<br>
<br>
<table class="table table-hover">
	<th>Date</th>
	<th>Game Time</th>
	<th>Location</th>
	<th>Opponent</th>
	<th></th>
<% @games.each do |game| %>
		<tr>
			<td><%= (game.scheduled_date).strftime("%m/%d/%Y") %></td>
			<td><%= game.scheduled_time %></td>
			<td> <%= game.location %></td>
			<td> <%= game.opponent %></td>
			<% if current_club_player %>
			<td><%= link_to "edit", edit_game_path(game) %> | <%= link_to "remove", game, method: :delete, data: {confirm: "This can't be undone"} %>  
			</td>
			<% end %>	
		</tr>
<% end %>	
</table>

<div id='edit_game'></div>

app/views/dashboard/_player.html.erb
<h1 class="page-header">Dashboard</h1> 
<h5>What your profile looks like to coaches: <%= link_to "Public Profile", profile_path(current_club_player.profile_name), id: "video-link" %></h5>
<br><br>
<ul class="nav nav-tabs">
	<li class="active"><a href="#video_listing" data-toggle="tab">My Videos</a></li>
	<li><a href="#schedule_listing" data-toggle="tab">My Upcoming Game</a></li>
	<li><a href="#profile_tracker" data-toggle="tab">My Profile Stats</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="video_listing">
		<% if @listings.size > 0 %>
		 <br><%= render 'video' %>
		<% else %>
		     <%= render 'seed_video' %>
		<% end %>
	</div>
	<div class="tab-pane" id="schedule_listing">
		<% if @games.size > 0 %>
		<br><%= render 'game' %> 
		<% else %>
			 <%= render 'seed_game' %>
		<% end %>
	</div>
	<div class="tab-pane" id="profile_tracker">
		<%= render 'statistics' %>
	</div>
</div>


</div>

<%= render 'upgrade_link_tracker_modal' %>
<script>

$("#broswer-explainer").tooltip(
		{
			title: "Careful when reading these stats. Because of the way " +
				   "some browsers work some clicks maybe counted twice. Additionally, " +
					"ip lookup information is always as close as possible but cant account " +
					"for various routing systems. These stats will help you paint a picture."
		}
);

</script>

app/views/dashboard/_seed_coach_fav.html.erb
<br>
<div class="row">
	<div class="col-md-9">
		<div class="alert alert-info">
		<p>Get a massive jump on keeping track of who you want to see more of here and build your next and future recruiting classes - <%= link_to 'Add your first player to your watchlist <i class="fa fa-long-arrow-right"></i>'.html_safe, club_players_path, class: "btn btn-link btn-lg" %></p>
		</div>
	</div>
	<div class="col-md-7">
		<a href="//fast.wistia.net/embed/iframe/mm9lhkhchj?popover=true" class="wistia-popover[height=450,playerColor=069750,width=800]">How do I add a player to my watchlist?</a>
		<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/popover-v1.js"></script>
	</div>
</div>

app/views/dashboard/_seed_game.html.erb
<br>
<div class="alert alert-info">
<p>College coaches want to see your upcoming schedule, make it easy for them here - <%= link_to "Add my first game", new_game_path %>
</div>
<%= link_to "How do I add a game?", edit_club_player_registration_path %>
<table class="table table-hover">
	<th>Date</th>
	<th>Game Time</th>
	<th>Location</th>
	<th>Opponent</th>
<% @games.each do |game| %>
		<tr>
			<td><%= game.scheduled_date %></td>
			<td><%= game.scheduled_time %></td>
			<td> <%= game.location %></td>
			<td> <%= game.opponent %></td>
			<% if current_player %>
			<td><%= link_to "edit", edit_game_path(game) %> | <%= link_to "remove", game, method: :delete, data: {confirm: "This can't be undone"} %>  
			</td>
			<% end %>	
		</tr>
<% end %>	
</table>

app/views/dashboard/_seed_video.html.erb
<br>
<div class="row">
	<div class="col-md-12">
		<div class="alert alert-info">
		<p>Who cares if you had 1 bad game out of 100? Show off the other 99! - <%= link_to 'Add my first video <i class="fa fa-long-arrow-right"></i>'.html_safe, new_listing_path %>	
		</div>
	</div>
	<div class="col-md-7">
		<%= link_to "How do I add a video?", edit_club_player_registration_path %>
	</div>
</div>

app/views/dashboard/_statistics.html.erb
<% if current_club_player.subscribed? && current_club_player.link.nil? %>
 <%= link_to "Generate my unique link", generate_short_link_path, method: :post, class: "btn btn-link btn-lg" %>
 <br> 
 <br>
 <small>
 <a href="//fast.wistia.net/embed/iframe/1313qtqgtk?popover=true" class="wistia-popover[height=450,playerColor=069750,width=800]">What does this do?</a>
 <script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/popover-v1.js"></script>
 | <%= link_to "more help", edit_club_player_registration_path %>
<% elsif current_club_player.subscribed? && !current_club_player.link.nil? %>
</small>
	<br>
  <small><a href="//fast.wistia.net/embed/iframe/4xjbj5uwvx?popover=true" class="wistia-popover[height=450,playerColor=069750,width=800]">How do I use this?</a>
	<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/popover-v1.js"></script><br></small>
	Your tracking link is: <%= current_club_player.link.display_slug %><br>
	Your link counts are: <%= current_club_player.link.clicks %><br>

	<a data-toggle="collapse" href="#statDetails">Show stat details</a><small> <i>beta</i> <i id="broswer-explainer" data-toggle="tooltip" data-placement="right" class="fa fa-question-circle"></i></small>			
	<div id="statDetails" class="collapse">
		<div class="row">
			<div class="col-md-4">
				<br>
				<ul id="stat-list">
					<% @stats.each do |stat| %>
					<li>+1 from 
						<a href="http://whatismyipaddress.com/ip/<%= stat.clicker %>" target="_blank">
							<%= stat.clicker %>
						</a> <small><%= time_ago_in_words(stat.created_at)%> ago</small>
						<hr>
				    </li>					
					<% end %>
				</ul>
			</div>	
		</div>	
	</div>		 
<% else %>
    <br>
	<button data-toggle="modal" data-target="#linkTrackerModal" class="btn btn-lg btn-marketing"> Generate my unique link <i class="fa fa-long-arrow-right"></i></button>
	<br><br>
	<p>Know if that college coach clicked your profile link in the email you sent.<br>
		<p>Example of stats below and <a href="//fast.wistia.net/embed/iframe/4xjbj5uwvx?popover=true" class="wistia-popover[height=450,playerColor=069750,width=800]">example video</a>
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/popover-v1.js"></script> for details.</p>
		<a target="_blank" href="https://s3-us-west-2.amazonaws.com/fiftyfourfooty/link-desc.png"><img class="well link-example" src="https://s3-us-west-2.amazonaws.com/fiftyfourfooty/link-desc.png"></a><br>
	<i>important</i> <i id="broswer-explainer" data-toggle="tooltip" data-placement="right" class="fa fa-question-circle"></i></p>
	<p>Generate a unique link for your profile and know when and where it was clicked. </p>
<% end %>

app/views/dashboard/_upgrade_link_tracker_modal.html.erb
<div class="modal fade" id="linkTrackerModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><i class="fa fa-flag-o"></i> Offsides! <small>Just kidding that's corny.</small></h4><p>
      </div>
      <div class="modal-body">
        
			<p>You need to <%= link_to "upgrade", upgrade_path, id: 'upgrade-in-p' %> your account to generate a unique link so you can track number of clicks, and when/where it was clicked.</p>
		<p>This is super useful for when you send emails to college coaches and you'd like to know if they clicked through to see your profile to watch your games and see your schedule.
		</p>
		<br>
		<p><%= link_to "Upgrade Now <i class='fa fa-long-arrow-right'></i>".html_safe, upgrade_path, id: 'upgrade-below-p', class: "btn btn-link btn-lg" %></p>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_video.html.erb
<br>
<%= link_to "Add new video", new_listing_path, class: "btn btn-success btn-lg" %>
<br>
<br>
<% @listings.each do |listing| %>
<div class='col-md-2 col-sm-5 col-xs-5 card-wrapper-user'>
	<div class="row" style="text-align: center;">
		<img class="dash-thumb" src="https://i1.ytimg.com/vi/<%=youtube_thumb_embed(listing.video)%>/mqdefault.jpg">	
	</div>
	<div class="row">
		<ul>
			<li><%= listing.description %></li>
			<li><%= link_to "Remove", listing, method: :delete, data:{confirm: "This cannot be undone"} if current_club_player == listing.club_player %></li>
		</ul>
	</div>
</div>
<% end %>

app/views/dashboard/show.html.erb
<%= render 'player' if current_club_player && club_player_signed_in? %>
<%= render 'coach' if current_college_coach && college_coach_signed_in? %>

<% if fresh_user_session_for_segment? %>
	<script>
		analytics.identify("<%= current_user.id %>",{
			name: "<%= current_user.full_name %>",
			type: "<%= current_user.class.name %>",
			email: "<%= current_user.email %>"
		});
	</script>
<% end %>

app/views/dashboard/upgrade.html.erb
<div class="col-md-10 col-md-offset-1 row well" style="margin-top:50px;">	
		<div class="col-md-1">
			<img alt="54footy logo" class="upgrade-logo" src="https://s3-us-west-2.amazonaws.com/fiftyfourfooty/iron-canary-small.png">
		</div>
		<div class="col-md-9 col-md-offset-1">
			<div style="text-align:center;">
			  <h2>Show off to any coach in the world</h2>
		    </div>
			<p>Hopefully, you have been getting your best footage in front of all your dream schools. Now, show off even more footage and track how many clicks you get when sending out your profile to coaches. Upgrade your account to get full access immediately. </p>
		</div>					
	</div>
</div>

<div class="row">
	<h3 style="text-align:center; color:#980300;">Connect with the perfect fit for your career after the club level for the next 4 years</h3>
	<br>
	<div class="col-md-upgrade-custom col-md-2 well-other-soccer-expenses">
		<h5><strong>1 plane ticket<br> to Surf Cup</strong></h5>
		<i style="padding-top:4px;font-size: 5.25em;" class="fa fa-plane"></i>
		<p>$185.00</p>
	</div>
	<div class="col-md-offset-1  col-md-3 well-upgrade">		
			<h4><strong><i class="fa fa-check"></i>unlimited videos</strong></h4>
			<h4><strong><i class="fa fa-check"></i> profile link tracking</strong> </h4>
		<hr>
		<p>Right now only <strong>$170/year</strong></p>
		<p>Regular <span style="text-decoration:line-through;">$200/year</span></p>
		<%= link_to "Upgrade My Account", new_charge_path, {class: "btn btn-lg btn-block btn-success", id: "to-checkout"} %>
		<br>		
	</div>
	<div class="col-md-offset-1 col-md-2 well-other-soccer-expenses">
		<h5><strong>1 pair of boots<br> for the season</strong></h5>
		<img style="height:80px;width:80px;" ref="boots" src="https://s3-us-west-2.amazonaws.com/fiftyfourfooty/soccer38.png">
		<p>$220.00</p>
	</div>
</div>