config/routes.rb
Breakaway::Application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "marketing#splash"
  get '/about', to: 'marketing#about'
  
  devise_for :club_players, :controllers => {:registrations => "players/registrations",
                                        :sessions => "players/sessions",
                                        :passwords => "players/passwords"} 
                                        
 
  devise_for :college_coaches, :controllers => {:registrations => "coaches/registrations",
                                        :sessions => "coaches/sessions", 
                                        :passwords => "coaches/passwords"}
  authenticated :club_player do 
    resources :links    
    get '/upgrade', to: 'dashboard#upgrade'
    post '/create_link', to: 'dashboard#create_short_url', as: 'generate_short_link'    
    resources :listings, except: :show
    resources :charges
    resources :games
    patch '/cancel_subscription', to: 'dashboard#cancel_subscription'
  end
  authenticated :college_coach do
    get 'friendships/:friend_id' => 'user_friendships#new', :as => :new_friendship  
    put '/e/:profile_name', to: "profiles#email_club_coach", as: 'send_coach_email'
  end

  get "profiles/show" 
  
  get '/players', to: "profiles#index", as: 'club_players'
  get "dashboard/show"
  get "dashboard", to: "dashboard#show", as: 'dashboard'
  get "/dashboard/download_schedule", to: "dashboard#download_schedule", as: "download_schedule" #, format: 'csv'
  get "/terms", to: 'marketing#terms_and_privacy', as: 'terms'
    
  get '/t/:slug', to: 'links#show_profile'
  
  get '/:profile_name', to: "profiles#show", as: 'profile'
    
  resources :user_friendships
  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  
  before_create do |record|
    !record.video.downcase.include?("<script>")
  end
  
  validates :video, :description, presence: :true
  validates :video, format: {
         #with: /\Ahttps:\/\/www.youtube.com\//,
         with: /\A(?:https?:\/\/)?(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([\w-]{10,})/,
         message: "Must be a youtube video url and have https in url."
       }
  
  belongs_to :club_player
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_club_player!, only: [:new, :edit, :create, :update, :destroy]
  before_action :check_listing_total, only: [:new, :create]

  # GET /listings
  # GET /listings.json
  def index
    @listings = current_club_player.listings.order('created_at DESC').all    
  end
  
  # GET /listings/new
  def new
    @listing = current_club_player.listings.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_club_player.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to dashboard_path, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    if params[:listing] && params[:listing].has_key?(:user_id)
            params[:listing].delete(:user_id)
    end
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to dashboard_path, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.json { head :no_content }
    end
  end

  private
  
  def check_listing_total
    if current_club_player.listings.count >= 3 &&  !current_club_player.subscribed?
      redirect_to( dashboard_path, alert: "You're currently only able to 3 uploaded videos at this time, #{ view_context.link_to "Here", upgrade_path, id: 'flash-listing-upgrade'} you can upgrade your account to continue adding more videos.".html_safe )
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = current_club_player.listings.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        render file: 'public/404', status: :not_found
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:video, :description)
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :video %>
    <%= f.text_field :video, class: "form-control", placeholder: "paste in your videos youtube url here" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Be as descriptive as possible. "  %>
		<p><small>what is the date? which player are you? what is this clip showing? who are you playing? what tournament is this?</small></p>
  </div>
  <div class="actions">
    <%= f.button "Add this Video", class: "btn btn-success btn-lg btn-block" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.video %></td>
        <td><%= listing.description %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>Add new video</h1>
<a href="//fast.wistia.net/embed/iframe/3e68l8x5b8?popover=true" class="wistia-popover[height=450,playerColor=069750,width=800]">How do I add a video?</a> | <small><%= link_to "more help", edit_club_player_registration_path %></small>
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/popover-v1.js"></script>
<hr>
<div class="row">
	<div class="col-md-5">
		<%= render 'form' %>
	</div>
</div>

<small><%= link_to 'Back to dashboard', dashboard_path %></small>