config/routes.rb
Breakaway::Application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "marketing#splash"
  get '/about', to: 'marketing#about'
  
  devise_for :club_players, :controllers => {:registrations => "players/registrations",
                                        :sessions => "players/sessions",
                                        :passwords => "players/passwords"} 
                                        
 
  devise_for :college_coaches, :controllers => {:registrations => "coaches/registrations",
                                        :sessions => "coaches/sessions", 
                                        :passwords => "coaches/passwords"}
  authenticated :club_player do 
    resources :links    
    get '/upgrade', to: 'dashboard#upgrade'
    post '/create_link', to: 'dashboard#create_short_url', as: 'generate_short_link'    
    resources :listings, except: :show
    resources :charges
    resources :games
    patch '/cancel_subscription', to: 'dashboard#cancel_subscription'
  end
  authenticated :college_coach do
    get 'friendships/:friend_id' => 'user_friendships#new', :as => :new_friendship  
    put '/e/:profile_name', to: "profiles#email_club_coach", as: 'send_coach_email'
  end

  get "profiles/show" 
  
  get '/players', to: "profiles#index", as: 'club_players'
  get "dashboard/show"
  get "dashboard", to: "dashboard#show", as: 'dashboard'
  get "/dashboard/download_schedule", to: "dashboard#download_schedule", as: "download_schedule" #, format: 'csv'
  get "/terms", to: 'marketing#terms_and_privacy', as: 'terms'
    
  get '/t/:slug', to: 'links#show_profile'
  
  get '/:profile_name', to: "profiles#show", as: 'profile'
    
  resources :user_friendships
  

end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController
  def splash
    render layout: false
  end
  
  def about_page
  end
  
  def terms_and_privacy
  end  
end

app/helpers/marketing_helper.rb
module MarketingHelper
end

app/views/marketing/about.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3 well-forms">
		<div class="row">
			<div class="col-md-4">
		      <img src="https://s3-us-west-2.amazonaws.com/fiftyfourfooty/iron-canary-small.png" />
	        </div>
			<div class="col-md-8">
				<br>
				<br>
		  	  <h1>About 54footy</h1>
	  		</div>
	    </div>
		<hr>
		<p>Ever had a not so great game? Ever had a not so great game when somebody really important was watching your every move, for only fifteen minutes with a clipboard and you rolled your ankle early in the week when you were getting some extra fitness in to get ready for this weekend's game?</p>
		<br>
		<p>Well, yes it happens. But the point is your entire 4 year college career shouldn't come down to one not so great game on the wrong weekend. EVERYONE has off games. Yes, even Aaron Ramsey. </p>
		<br>
		<p>We believe there is a great fit for every deserving club player at the collegiate level and to not find the right school simply because a coach couldn't make it to your game on the east coast or because you only had 5 touches when your dream school coach watched your game for 15 minutes just doesn't make any sense.</p>
		<br>
		<p>Our players:
			<ul>
				<li>Get more exposure to their favorite schools.</li>
				<li>Get more official visit invites.</li>
				<li>Discover great schools they didn't know about, that are interested in them.</li>
			</ul>			
		</p>
		<p> Show your favorite schools the real player you are and give yourself a better chance of being seen. You've put in the work for the last 14+ years every single week, make the next 4 years count.
		</p>
		<br>
	    <%= link_to "Get Started", new_club_player_registration_path,class: "btn btn-success btn-lg btn-block"  %>
		<h1>Contact Us</h1>
		<p>Got a question? Need help with something? <a href="mailto:tony@54footy.com">Email us</a></p>
	</div>
</div>

app/views/marketing/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breakaway</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= favicon_link_tag 'fffooty.ico' %>
  <%= favicon_link_tag 'fffooty.ico', rel: 'apple-touch-icon', type: 'image/png'%>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script type="text/javascript">    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["WRITE_KEY"] %>");
    window.analytics.page();
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	  <%= link_to "54footy", root_path, class: "navbar-brand" %>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
	  <% if user_signed_in?  %>
        <li>
			<%= link_to "Dashboard", dashboard_path %>
        </li>
        <li>
			
        </li>
        <li>
			<%= link_to "All Players", club_players_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
		  
  	        <li>
				<%= link_to "Sign out coach", destroy_college_coach_session_path, method: :delete if current_college_coach %>
				<%= link_to "Sign out player", destroy_club_player_session_path, method: :delete if current_club_player %>
  	        </li>
	 	  <% else %>
	        <li>
				<%= link_to 'Player', new_club_player_session_path %>
	        </li>
	        <li>
	          <%= link_to 'Coach', new_college_coach_session_path %>
	        </li>
	        <li>
				<%= link_to "All Players", club_players_path %>
	        </li>
			<li>
				<a href="http://legends.54footy.com/players" target="_blank">How does this work?</a>
			</li>
		<% end %>

      </ul>
    </nav>
  </div>
</header>
<div class="container" style="margin-top:100px">
	<% if notice %>
		<div class="alert alert-success">
			<button class="close" data-dismiss="alert">x</button>
			<p><%= notice %></p>
		</div>
	<% end %>
	<% if alert %>
		<div class="alert alert-danger">
			<button class="close" data-dismiss="alert">x</button>
			<p><%= alert %></p>
		</div>
	<% end %>
	
	<div class="row thingsy" style="color:white; height:400px;">
		<div class="col-md-5 col-md-offset-1">
			<div class="row">
				<div class="col-md-12 col-sm-7" style="background:rgba(0,0,0,.5);padding:20px;">
					<span id="main-headline">Find your next <br>leading goal scorer.</span>
					<br><br>
					<p>Beautifully simple online recruiting for college soccer coaches.</p>
					<%= link_to "Watch Club Player Games Now", club_players_path, class: "btn btn-lg btn-marketing", id: "view-games-splash" %>
					<p id="player-feature-signup"><small>club soccer player? <%= link_to 'Get featured for free <i class="fa fa-long-arrow-right"></i>'.html_safe, new_club_player_registration_path, class: "feature-link" %></small></p>
			    </div>
			</div>
		</div>
	</div>	
	
</div>
<footer class="footer container">
  <small>
    <a class="front_contact" href="https://54footy.com/blog"><img class="splash-logo" src="https://s3-us-west-2.amazonaws.com/fiftyfourfooty/iron-canary-small.png"></a>
    <span class="front_contact">54footy</span>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path, class: "front_contact" %></li>
      <li><a class="front_contact" href="mailto:tony@54footy.com">Support</a></li>
      <li><a class="front_contact" href="https://54footy.com/blog">Blog</a></li>
    </ul>
  </nav>
</footer>
<script>
   $.backstretch("https://s3-us-west-2.amazonaws.com/fiftyfourfooty/hero-background.jpg")
   
   // call it here instead of head becasue of turbolinks
	window.analytics.page();
</script>
</body>
</html>